services:
  - type: web
    name: dads-shop-backend
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dads-shop-db
          property: connectionString
      - key: ADMIN_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    autoDeploy: true
databases:
  - name: dads-shop-db
    plan: free
